# Generated by Django 6.0.4 on 2026-05-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='curs',
            new_name='coursies',
        ),
    ]
